services:

  usuariosapp:
    container_name: usuarios
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbUsuarios
    depends_on:
      - dbUsuarios

  dbUsuarios:
    container_name: dbUsuarios
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
